### ISSUE TITLE
Mistakes in the GLA paper

### ISSUE THREAD

**Issue by faresobeid** [sustcsonglin/flash-linear-attention#1]
Thank you for all your great work on linear attention and I'm very excited about this repo!

I just wanted to bring up some errors in the GLA paper which might make the paper look less valuable, and maybe you could fix these in a new version if you want to.

1.
**Shouldn't the division by the temperature term be inside the brackets?**
<img width="1071" alt="Screenshot 2024-01-10 at 09 35 53" src="https://github.com/sustcsonglin/flash-linear-attention/assets/111092724/a389c083-edbf-4fff-ab68-8733c6876f67">

2. 
**Why is the Q_t transposed here?**
<img width="375" alt="Screenshot 2024-01-10 at 09 36 39" src="https://github.com/sustcsonglin/flash-linear-attention/assets/111092724/6cd32aac-19ee-48b7-accf-dd69937b1474">

3. 
**For the B calculation it should be the product of beta not B**
<img width="1045" alt="Screenshot 2024-01-10 at 09 38 06" src="https://github.com/sustcsonglin/flash-linear-attention/assets/111092724/7bcecede-a82c-4553-a3b4-36a48212ff19">

4. 
**Again here why is the Q transposed?**
<img width="443" alt="Screenshot 2024-01-10 at 09 39 51" src="https://github.com/sustcsonglin/flash-linear-attention/assets/111092724/c3feb5ad-6ec7-46f9-8d7d-8ed5d3b5c63c">

5. 
**The V = V[...] is missing here**
<img width="693" alt="Screenshot 2024-01-10 at 09 40 44" src="https://github.com/sustcsonglin/flash-linear-attention/assets/111092724/066a0225-aaad-4420-8f24-0c085a922868">

6. 
**Shouldn't a_normaliser and b_normaliser be a_q[...] not a[...]?**
<img width="605" alt="Screenshot 2024-01-10 at 09 41 32" src="https://github.com/sustcsonglin/flash-linear-attention/assets/111092724/e6c52016-4037-4f7a-bcf9-167d236a23c5">

7.
**Shouldn't it be k = K[:,:,i*C + j*c,....] not k*c?**
<img width="779" alt="Screenshot 2024-01-10 at 09 43 08" src="https://github.com/sustcsonglin/flash-linear-attention/assets/111092724/cd8f4a09-de57-4d5f-992d-7309d97e104c">

8.
**Shouldn't it be V_iC + k, not V_iCk?**
<img width="736" alt="Screenshot 2024-01-10 at 09 44 12" src="https://github.com/sustcsonglin/flash-linear-attention/assets/111092724/29a54a6e-b2c6-48e9-be03-a4fc77b14053">

If any of these are not actually mistakes then feel free to point that out, hope this helps!

**Comment by sustcsonglin** [comment]
Thank you for pointing it out! More proofreading should be done and we will fix these issues in our next iterations

Regarding (1), we indeed divide the temperature term outside the bracket.  See [link1](https://github.com/sustcsonglin/flash-linear-attention/blob/main/fla/layers/gla.py#L70) and [link2](https://github.com/berlino/gated_linear_attention/blob/main/kernels/inter_chunk_contribution/preprocess_cumsum_gk.py#L45)

**Comment by faresobeid** [comment]
Thank you for the reply, it looks like you divide the log(sigmoid) by 16 while in the paper its shown as sigmoid divided by 16 if im not mistaken, it should be sigmoid**(1/16) right?

**Comment by sustcsonglin** [comment]
Yes, thank you for pointing that out. We have quite a few small mistakes here. Many thanks to you for catching these bugs

**Comment by berlino** [comment]
@faresobeid we have updated arxiv version. let us know if you catch any mistakes. 

Thanks!

**Comment by fawwaz1st** [comment]
placeholder

**Comment by fawwaz1st** [comment]
placeholder
