### ISSUE TITLE
Using operators without having `transformers` installed

### ISSUE THREAD

**Issue by Ronsor** [sustcsonglin/flash-linear-attention#14]
I'm currently trying to use just the operators defined in `fla.ops`; however, because of the `__init__.py` script for the main package, it's not possible to do this without importing things from the HF `transformers` package, which makes the import slower (and broke it entirely until I upgraded the package).

It would be nice if there were a way to just import the operators without the layer modules or anything else.

**Comment by yzhangcs** [comment]
@Ronsor Hi, may I know why you need this. I think its hard to use `fla` as well if `transformers` is unavailable. Currently this pkgs is heavily tied with 🤗  `transformers`, e.g., we use its off the shelf utility fns to check Trion versions and raise some warnings and we alse make use of some activations in `transformers`.
