### ISSUE TITLE
Finetune RWKV6 with fla implementations (使用fla中的rwkv6微调)

### ISSUE THREAD

**Issue by JL-er** [sustcsonglin/flash-linear-attention#16]
在bo的代码基础上将cuda算子替换为fla后loss初始很高，8.几起步。之前直接使用gla算子替换cuda，因为gla和rwkv的state计算顺序错开所以那里的r需要roll一下（微调正常）。所以麻烦您看一下我的代码是否少了一些必要操作

![image](https://github.com/sustcsonglin/flash-linear-attention/assets/139205286/41ba0609-382a-42ed-96d5-62cabced318f)

**Comment by yzhangcs** [comment]
@JL-er Hi, not sure what happened, I think one subtle is the choice of activations for forget gates. They use $e^{-e^x}$ while we simply use $\sigma$. You may need to add a temperature term $\sigma^\tau$ to encourage the decay to approach 1 more closely, i.e., `F.logsigmoid(w) / tau`

**Comment by JL-er** [comment]
感谢提示，我缺少了-exp(w)，但loss仍处于4.多。在第一版gla算子中这是有效的，我保留clamp 防止梯度为nan，丢弃了logsigmoid（loss只有微小的误差）

**Comment by JL-er** [comment]
fla的rwkv6目前还是没办法直接微调已有模型= =

**Comment by yzhangcs** [comment]
@JL-er Could you provide more error infos

**Comment by JL-er** [comment]
主要问题应该是 F.logsigmoid(w)，如果我把F.logsigmoid去掉是否需要修改算子？（英文不太好，为了表述清楚一些直接用中文提问了，不好意思

**Comment by yzhangcs** [comment]
@JL-er No need to revise the kernels, just pass log space values $-e^w$ into the kernel. Some value clipping may be required for stability.

**Comment by JL-er** [comment]
sonta写的最初版本gla算子 我有改写过，并且适配到了wkv6，但是他缺少state的梯度所以我现在想换成最新的。
下面是我修改的kernel
![image](https://github.com/sustcsonglin/flash-linear-attention/assets/139205286/c76f9ac2-c7ec-4235-8294-b2c19d604c1c)
我的w会在外面提前做一次-exp来对应wkv6
![image](https://github.com/sustcsonglin/flash-linear-attention/assets/139205286/927a46b9-eff5-41c0-befb-a77a8bffe1bd)

**Comment by JL-er** [comment]
> @JL-er No need to revise the kernels, just pass log space values −ew into the kernel. Some value clipping may be required for stability.

我试试加入clamp

**Comment by JL-er** [comment]
解决了，目前会有一点损失，我需要对比一下。非常感谢
