### ISSUE TITLE
更新后的rwkv6，loss会nan

### ISSUE THREAD

**Issue by JL-er** [sustcsonglin/flash-linear-attention#19]
我现在用的是前几天的版本loss正常

**Comment by yzhangcs** [comment]
Oh, looks that you may need to switch back to logsigmoid, -exp is not stable yet

**Comment by JL-er** [comment]
![image](https://github.com/sustcsonglin/flash-linear-attention/assets/139205286/4a49b501-818c-4928-a7fe-da236c7e5584)
这是可行的loss非常稳定，基本没有误差

**Comment by JL-er** [comment]
![image](https://github.com/sustcsonglin/flash-linear-attention/assets/139205286/b0b3c6fe-187a-4cb2-a594-43ac52d27b8f)
应该是这次更新的问题

**Comment by yzhangcs** [comment]
This update fixes potential nans during inference, I think it's not the issue.
Possibly cuz of potential inf grad of -exp, would check it, thank you

**Comment by JL-er** [comment]
RWKV-PEFT 添加fla，目前是可用的。但是一旦更换新fla loss就会nan，如果后续fla有更新可以告诉我 ，我可以进行测试

**Comment by JL-er** [comment]
![image](https://github.com/sustcsonglin/flash-linear-attention/assets/139205286/c2ba8e5e-b333-4f9e-9c8b-c8e96f1dcd67)
不知道为什么fla的rwkv6，竟然没有cuda快，我之前测试gla的时候会快很多

**Comment by yzhangcs** [comment]
Have you compared the kernel speed

**Comment by JL-er** [comment]
我找时间测一下，对了还有个问题，我在做state tuning的时候，替换上fla算子会出现报错
![image](https://github.com/sustcsonglin/flash-linear-attention/assets/139205286/cd836611-c423-4134-a228-6b3a9d1cdec5)
应该是state没有保存梯度的原因，所以想问一下怎么解决？

**Comment by yzhangcs** [comment]
You can enable gradient for h0 mannually

**Comment by yzhangcs** [comment]
Taking h0 as learnable params would be ok? like `h0 = nn.Parameter(key_dim, head_dim)`

**Comment by JL-er** [comment]
还有一点是，我这里冻结了其他所有权重只保留state的梯度

**Comment by yzhangcs** [comment]
ic, currently there is no access to grad of states. 
we will add an option later

**Comment by JL-er** [comment]
thank you

**Comment by JL-er** [comment]
rwkv-peft上测试非常完美，已经不需要clip了，不过之前infctx训练6000ctx len时偶尔会nan（我会重新测试

**Comment by sustcsonglin** [comment]
FYI we've recently fixed a bug that causes NaN when log decay is very small. https://github.com/fla-org/flash-linear-attention/issues/77#issuecomment-2585539785
