### ISSUE TITLE
Use Cache with GLA model raised error

### ISSUE THREAD

**Issue by OREYR** [sustcsonglin/flash-linear-attention#26]
Hi, I see that the RecurrentCache was renamed to Cache for gla model. However, it raised error as Cache does not have method “from_legacy_cache”.

**Comment by yzhangcs** [comment]
@OREYR Thank you for reporting this bug.
> is there a reason why we need to change RecurrentCache to Cache here? Does RecurrentCache apply to RNN models only?
The ongoing plan is to support more cache types, e.g., shortconv, sliding window, rnn, token-shift.
So It would be better to rename it to a more general name.

**Comment by OREYR** [comment]
Thank you @yzhangcs . I wonder if it’s ok to continue to use RecurrentCache to train or evaluate GLA and RetNet in the repository at the moment.

**Comment by yzhangcs** [comment]
@OREYR Have you updated all the code. Which line did you met this bug.

**Comment by OREYR** [comment]
I tried the above code and got **type object 'Cache' has no attribute 'from_legacy_cache'**. There is no Cache class defined in the specified file. I only see RecurrentCache class.
