### ISSUE TITLE
bugs in BasedLinearAttention/LinearAttention/HGRN2Attention Implementation 

### ISSUE THREAD

**Issue by rakkit** [sustcsonglin/flash-linear-attention#28]
I've noticed a few bugs in the implementations of BasedLinearAttention, LinearAttention, and HGRN2.

For [BasedLinearAttention](https://github.com/sustcsonglin/flash-linear-attention/blob/main/fla/layers/based.py#L31) ` self.hidden_size` is not assigned

For [LinearAttention](https://github.com/sustcsonglin/flash-linear-attention/blob/main/fla/layers/linear_attn.py#L141) k(v)'s rearrange was repeated,  and feature_map_q(feature_map_k)'s position seems strange.
Also in [Line152](https://github.com/sustcsonglin/flash-linear-attention/blob/main/fla/layers/linear_attn.py#L152), we suppose to have something like `o = o[0] if isinstance(o, tuple) or isinstance(o, list)` as linear-att fwd will returns a list

For [HGRN2](https://github.com/sustcsonglin/flash-linear-attention/blob/main/fla/layers/hgrn2.py#L47), when all of three parameters provided, even with `expand_ratio*num_heads=hidden_size`, it raises error.

**Comment by yzhangcs** [comment]
Thank you for reporting this! Will fix the bugs soon, or any PRs are welcome

Yu Zhang
Soochow University

________________________________
From: rakkit ***@***.***>
Sent: Monday, July 1, 2024 7:52:07 AM
To: sustcsonglin/flash-linear-attention ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sustcsonglin/flash-linear-attention] bugs in BasedLinearAttention/LinearAttention/HGRN2Attention Implementation (Issue #28)


I've noticed a few bugs in the implementations of BasedLinearAttention, LinearAttention, and HGRN2.

For BasedLinearAttention<https://github.com/sustcsonglin/flash-linear-attention/blob/main/fla/layers/based.py#L31> self.hidden_size is not assigned

For LinearAttention<https://github.com/sustcsonglin/flash-linear-attention/blob/main/fla/layers/linear_attn.py#L141> k(v)'s rearrange was repeated, and feature_map_q(feature_map_k)'s position seems strange.
Also in Line152<https://github.com/sustcsonglin/flash-linear-attention/blob/main/fla/layers/linear_attn.py#L152>, we suppose to have something like o = o[0] if isinstance(o, tuple) or isinstance(o, list) as linear-att fwd will returns a list

For HGRN2<https://github.com/sustcsonglin/flash-linear-attention/blob/main/fla/layers/hgrn2.py#L47>, when all of three parameters provided, even with expand_ratio*num_heads=hidden_size, it raises error.

**Comment by yzhangcs** [comment]
@rakkit For HGRN2, we recommend you to use default `expand_ratio` of 128, or to let `expand_ratio * num_heads` equal to `hidden_size` to make the overall #params equal to Llama attention
