### ISSUE TITLE
Quick question: Is there a non-causal optimized form of Flash Linear Attention?

### ISSUE THREAD

**Issue by yzeng58** [sustcsonglin/flash-linear-attention#31]
Great work! 

It appears that both GLA and RetNet are optimized only for causal cases. Is there an optimized linear attention for non-causal scenarios?

**Comment by sustcsonglin** [comment]
Thanks for your interest - we plan to implement this soon

**Comment by yzeng58** [comment]
One quick question: is there any place that I can directly use the plain flash linear attention with Triton, without adding the forget gate?

**Comment by sustcsonglin** [comment]
https://github.com/sustcsonglin/flash-linear-attention/blob/main/fla/layers/linear_attn.py

**Comment by yzeng58** [comment]
Thanks so much for your quick response!

**Comment by yzeng58** [comment]
In this case, there is only chunk, fused_chunk and recurrent mode right? In the case, there is a green line without using chunkwise parallel at all. I thought it is different from the "recurrent" mode defined in https://github.com/sustcsonglin/flash-linear-attention/blob/main/fla/layers/linear_attn.py, right? 
![image](https://github.com/user-attachments/assets/ebfc0903-b97a-472f-9ac0-774913f43a9d)

**Comment by YicongHong** [comment]
> Thanks for your interest - we plan to implement this soon

Really looking forward to it! Any updates? Thanks! 😄

**Comment by hp-l33** [comment]
Hi,

I have preliminarily implemented a Triton version of non-causal linear attention [here](https://github.com/hp-l33/flash-bidirectional-linear-attention).

Many thanks to the authors of this repository for the inspiration—feel free to give it a try!
