### ISSUE TITLE
'RebasedFeatureMap' is missing?

### ISSUE THREAD

**Issue by 4IK1d** [sustcsonglin/flash-linear-attention#5]
Hi, thanks to all your efforts for such a good repo.

I'm trying to build a model basing on `RebasedLinearAttention`, but encounter error:

>>> ImportError: cannot import name 'RebasedFeatureMap' from 'fla.modules.feature_map' (.*/fla/modules/feature_map.py)

Should this feature under developing or use hazyResearch's implementation located in `https://github.com/corl-team/rebased/blob/main/flash_linear_attention/fla/layers/rebased_fast.py`?

**Comment by yzhangcs** [comment]
@4IK1d Hi, fixed. Please check it out :-) https://github.com/sustcsonglin/flash-linear-attention/commit/8181db5d2e7ac5ddd78612db36bf7b3431f604e5

**Comment by 4IK1d** [comment]
You guys are awesome!

**Comment by 4IK1d** [comment]
https://github.com/sustcsonglin/flash-linear-attention/blob/646efa4cf12bf3b73993968931fe2f4b3597c285/fla/layers/rebased.py#L33C9-L33C32

Hi, seems you forget *arg and **kwargs, then we cannot passin something like `layer_idx`   
(really trivial, :-P)

**Comment by yzhangcs** [comment]
@4IK1d ah, thank you for the reminder~
