### ISSUE TITLE
Variable-length sequence support

### ISSUE THREAD

**Issue by patronum08** [sustcsonglin/flash-linear-attention#51]
Hello, I noticed that retnet currently does not support variable-length sequences as input, which is quite important during pre-training. For example, features similar to `seq_idx` in mamba2 or `cu_seqlens` in flash attention. Do you have plans to support this feature?

**Comment by sustcsonglin** [comment]
Yes we plan to support this feature - stay tuned

**Comment by patronum08** [comment]
That's nice. Thanks

**Comment by yzhangcs** [comment]
@patronum08 Hello, check out the latest commits https://github.com/sustcsonglin/flash-linear-attention/commit/20f30c67edd668d0624705489a9932c8cbc2eff3.

https://github.com/sustcsonglin/flash-linear-attention/blob/20f30c67edd668d0624705489a9932c8cbc2eff3/fla/ops/gla/chunk.py#L1484-L1510

Any suggestions are welcome.
