### ISSUE TITLE
Checkpoints for 340M models

### ISSUE THREAD

**Issue by 0205090923** [sustcsonglin/flash-linear-attention#53]
Thanks for your great work.
I did not find the checkpoint of 340M baselines on huggingface reported in GLA paper， could you kindly share them?

**Comment by sustcsonglin** [comment]
For GLA you can find it at https://huggingface.co/bailin28  and use https://github.com/berlino/gated_linear_attention for eval.   I plan to upload these baselines in FLA formats later on
