### ISSUE TITLE
[Bug]: H100 Triton 3.0.0 compile crash when using num_warps=8 in autotune

### ISSUE THREAD

**Issue by SmerkyG** [sustcsonglin/flash-linear-attention#58]
### Describe the bug

Hi, just wanted to let you know I am seeing this triton compile error problem on H100's with chunked simple GLA:
`python: /project/lib/Analysis/Allocation.cpp:43: std::pair<llvm::SmallVector<unsigned int>, llvm::SmallVector<unsigned int> > mlir::triton::getCvtOrder(mlir::Attribute, mlir::Attribute): Assertion `!(srcMmaLayout && dstMmaLayout && !srcMmaLayout.isAmpere()) && "mma -> mma layout conversion is only supported on Ampere"' failed.`
It went away as soon as I removed the num_warps=8 option from autotune for that kernel. See https://github.com/triton-lang/triton/issues/4418

### Steps to reproduce the bug

run chunked simple GLA on H100

### Expected behavior

no Triton compilation crash

### Environment info

1. torch: 2.4.1
2. triton: 3.0.0

**Comment by yzhangcs** [comment]
Thx!
