### ISSUE TITLE
About `rescale_prenorm_residual` default value in Mamba 2

### ISSUE THREAD

**Issue by zhixuan-lin** [sustcsonglin/flash-linear-attention#60]
Hello,

Is there a reason `rescale_prenorm_residual` is set to False in Mamba2 (see [here](https://github.com/sustcsonglin/flash-linear-attention/blob/bd5b73ffa54a8f0a389c5a55d0eb6a05250eed30/fla/models/mamba2/configuration_mamba2.py#L118))? The official Mamba2 repo uses `True` by default ([here](https://github.com/state-spaces/mamba/blob/62db608da60f6fc790b8ed9f4b3225e95ca15fde/mamba_ssm/models/mixer_seq_simple.py#L90)). Asking because all other models in FLA uses `True` by default so I wonder if there is any special consideration here.

Thanks!

**Comment by yzhangcs** [comment]
@zhixuan-lin Thank you for bringing this to our attention. The issue has been fixed.
