### ISSUE TITLE
[Bug]: H100 memory access violations in chunk_gla

### ISSUE THREAD

**Issue by SmerkyG** [sustcsonglin/flash-linear-attention#68]
### Describe the bug

Hi,

Running the latest chunk_gla on an H100 I am getting various memory access faults. Unfortunately the errors appear to occur later in the code from using the results of chunk_gla's output, so there isn't much information available. This doesn't occur on 4090's for me. And fused_chunk_gla (and even chunk_simple_gla) seem to work. 

I tried removing num_warps=8 and even num_warps=4 from the autotune settings, to see if this was related to https://github.com/sustcsonglin/flash-linear-attention/issues/58, but this did not fix it.

The problem manifests itself as deferred issues like
`RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16BF, lda, b, CUDA_R_16BF, ldb, &fbeta, c, CUDA_R_16BF, ldc, compute_type, CUBLAS_GEMM_DEFAULT_TENSOR_OP)``

or, if I print the tensors, they say there is a memory access error if printed right before where this gemm would have occurred.

As mentioned above, these issues do not occur when I run on 4090s. So not sure if it's a problem in triton, or an actual memory access mistake somewhere in the kernel that is only revealed due to H100's specific setup?

Thanks!

### Steps to reproduce the bug

running lm_eval_harness on a model that incorporates chunk_gla
I'll see if I can find a simple reproduction case...

### Expected behavior

no crash :)

### Environment info

1. torch: 2.4.1
2. triton: 3.0.0
3. H100 (works fine on 4090!)

**Comment by yzhangcs** [comment]
Thank you for reporting this. I will be fixing it soon.

**Comment by yzhangcs** [comment]
@SmerkyG Hi, could you check it again.

**Comment by SmerkyG** [comment]
Seems to work now, thank you!!!
