### ISSUE TITLE
Questions About custom attention mask

### ISSUE THREAD

**Issue by Rbrq03** [sustcsonglin/flash-linear-attention#71]
Hey there, congrats for the great work!

When using gated linear attention, I found the `attn_mask` argument in the `forward` function of it. However, it seems that it doesn't support an attn_mask with shape `seq_len * seq_len`. Could you tell me if Gated Linear Attention supports it?

If not, could you point me out if there is one type of linear attention that supports custom attention mask?

Thanks for your potential answer.

**Comment by sustcsonglin** [comment]
Unfortunately not. FLA does not support arbitrary attention mask. **attn_mask** here is used for left or right padding.

**Comment by Rbrq03** [comment]
Thanks for your answer.
