### ISSUE TITLE
Varlen Support

### ISSUE THREAD

**Issue by zml24** [sustcsonglin/flash-linear-attention#82]
Will FLA Team support varlen input for training in the future?

**Comment by yzhangcs** [comment]
Yes, in the near future. Please stay tuned :-D

**Comment by yzhangcs** [comment]
@zml24 Hi, check out the latest commits https://github.com/sustcsonglin/flash-linear-attention/commit/20f30c67edd668d0624705489a9932c8cbc2eff3.

https://github.com/sustcsonglin/flash-linear-attention/blob/20f30c67edd668d0624705489a9932c8cbc2eff3/fla/ops/gla/chunk.py#L1484-L1510

We basically give full support for varlen mode for GLA.
Still optimzing the speed and the APIs are still subject to change.
Discussions are welcome if you have any suggestions
Other kernels and layer supports are on the way.
