### ISSUE TITLE
[Bug]: GSA backward error

### ISSUE THREAD

**Issue by zml24** [sustcsonglin/flash-linear-attention#86]
### Describe the bug

Hi, I am using GSA for training. After [this commit](https://github.com/sustcsonglin/flash-linear-attention/commit/0407113381a384b27131c509f698c6884188073f), the code would report error 
```
loc("xxx/flash-linear-attention/fla/ops/gsa/chunk.py":362:38): error: invalid element type in packLLEElements. Expected 'i16' but got 'bf16'
loc("xxx/flash-linear-attention/fla/ops/gsa/chunk.py":362:38): error: 'llvm.extractelement' op failed to verify that result type matches vector element type
```

### Steps to reproduce the bug

python benchmarks/ops/benchmark_gsa.py

### Expected behavior

Everything run good and show benchmark statistic as before.

### Environment info

1. torch: 2.1.0
2. triton: 2.2.0

**Comment by zml24** [comment]
During the compilation phase, the unexpected conversion of `bf16` data to `i16` through `tl.trans` appears to be a bug from earlier versions of triton. It's unclear why I'm still encountering this bug in my environment (triton==2.2.0). Setting all `states_in_fp32` parameters related to `h` to `True` has proven to be an effective workaround for this issue.

**Comment by yzhangcs** [comment]
@zml24 Thank you for reporting this bugs, can you upgrade triton to 3.0, or is it ok to pass `head_first=True` as well as inputs of shape `[B, H, T, D]`?

**Comment by zml24** [comment]
> @zml24 Thank you for reporting this bugs, can you upgrade triton to 3.0, or is it ok to pass `head_first=True` as well as inputs of shape `[B, H, T, D]`?

Thank you for the suggestion. Unfortunately, I am unable to upgrade to triton 3.0 due to internal constraints. As for using `head_first=True`, this approach is not suitable for me because I want better results with varlen mode. However, I believe it is appropriate to close this issue, as it is a bug in triton rather than in fla.
