### ISSUE TITLE
[Bug]: `recurrent_states` are difference between `chunk` and `fused_recurrent` in GSA

### ISSUE THREAD

**Issue by zml24** [sustcsonglin/flash-linear-attention#92]
### Describe the bug

The class `ChunkGSAFunction` returns `ov, hkt, hvt` in the end, and the outer funciton `chunk_gsa` has perfect doc.
```
    Returns:
        o (torch.Tensor):
            Outputs of shape `[B, H, T, V]` if `head_first=True` else `[B, T, H, V]`.
        final_state (Tuple[torch.Tensor]):
            Final state tuple having tensors of shape `[N, H, K, M]` and `[N, H, M, V]` if `output_final_state=True`.
            `None` otherwise.
```

But the class `FusedRecurrentGSAFunction` returns `o, (hkt, hvt)` when setting `if T == 1 and not q.requires_grad:` (usually in decoding) and returns `ov.to(q.dtype), hkt, hvt` otherwise. This will result in calling `recurrent_states[0]` fail in decoding, but not in training/prefill. Hence I have to write different code to cache my `recurrent_states` in prefill & decode.

### Steps to reproduce the bug

-

### Expected behavior

Convert to `o, hkt, hvt`

### Environment info

-

**Comment by yzhangcs** [comment]
Thank you!
