### ISSUE TITLE
Will FLA further speedup Mamba or Mamba2?

### ISSUE THREAD

**Issue by codingWla** [sustcsonglin/flash-linear-attention#93]
Hi, 
    Thanks for your great contributions. 
    Does FLA further speedup Mamba or Mamba2 in comparison with official Mamba or Mamba2 (https://github.com/state-spaces/mamba)?
    or you use the official code of Mamba or Mamba2 in FLA, do you have any modification for speedup?
    Looking forward to your feedback. Thanks!

**Comment by sustcsonglin** [comment]
FLA's implementations of mamba1-2 are based on huggingface transformers library.  Training speed should be similar to the official repo. Inference speed should be much slower (see https://github.com/state-spaces/mamba/issues/578). We currently have no plan to further optimize Mamba1-2 in FLA.

**Comment by codingWla** [comment]
Anyway, thanks for your great contributions.
