### ISSUE TITLE
问哈代码是什么意思

### ISSUE THREAD

**Issue by guoguo1314** [sustcsonglin/flash-linear-attention#95]
在def fused_recurrent_fwd_kernel函数中，kv维度分别如下：
k,  # key [B, H, T, K]/[B, T, H, K]
v,  # value [B, H, T, V]/[B, T, H, V]
很明显不一样， 但是要执行行kv相乘代码，b_h += b_k[None, :] * b_v[:, None]。
然后假设k的shape是2, 8, 1, 64， v的shape是2, 8, 1, 128，
我问的cursor，它说
1. 首先看grid的设置：
B(batch_size) = 2
H(num_heads) = 8
K = 64
V = 128
grid = (NV, NK, N * H)  # = (2, 1, 2*8) = (2, 1, 16)
这意味着总共会启动 2 1 16 = 32 个线程块。
2.每个线程块由三个ID唯一标识：
i_v, i_k, i_nh = tl.program_id(0), tl.program_id(1), tl.program_id(2)
i_v: 0,1 (NV=2，因为V=128需要分两块)
i_k: 0 (NK=1，因为K=64只需要一块)
i_nh: 0到15 (NH=16，表示batch和head的组合)
3. 对于特定的batch和head（比如说batch=0, head=0，此时i_nh=0），会有两个线程块同时工作：
线程块1: (i_v=0, i_k=0, i_nh=0)
线程块2: (i_v=1, i_k=0, i_nh=0)
这两个线程块：
处理相同的k值(k[0:64])
但处理不同的v值段：
线程块1处理v[0:64]
线程块2处理v[64:128]

**我要问的问题来了**：也就是说一个k要与两个不同的v进行相乘（即(k[0:64])与v[0:64]相乘，还要与v[64:128]相乘）？

**Comment by sustcsonglin** [comment]
yes, every key dimension should be multiplied by other value dimension - this should be the definition of outer product.
